---
abstract: 'Check for presence of dependencies'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-CheckDeps
requires:
  CPAN::Meta: 0
  CPAN::Meta::Check: 0.004
  Exporter: 5.57
  List::Util: 0
  Test::Builder: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-CheckDeps
  repository: git://github.com/Leont/test-checkdeps.git
version: 0.005
